
services:
  rag_service:
    build:
      context: ./microservices/rag_service
    container_name: xavigate_rag_service
    depends_on:
      - postgres
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8010"]
    ports:
      - "8010:8010"
    env_file:
      - .env
      - ./microservices/rag_service/.env
    volumes:
      - ./microservices/rag_service:/app
      - ./microservices/db_service:/app/db_service
      - ./microservices/shared:/app/shared
      - ./docs:/app/docs

  vector_service:
    build:
      context: ./microservices/vector_service
    container_name: xavigate_vector_service
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8017"]
    ports:
      - "8017:8017"
    env_file:
      - .env
      - ./microservices/vector_service/.env
    volumes:
      - ./microservices/vector_service:/app
      - ./microservices/shared:/app/shared
      - ./microservices/db_service:/app/db_service
      - ./microservices/rag_service/chroma_db:/app/chroma_db
      - ./docs:/app/docs

  storage_service:
    build:
      context: ./microservices/storage_service
    container_name: xavigate_storage_service
    depends_on:
      - postgres
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8011"]
    ports:
      - "8011:8011"
    env_file:
      - ./microservices/storage_service/.env
    environment:
      POSTGRES_DB: xavigate
      POSTGRES_USER: xavigate_user
      POSTGRES_PASSWORD: changeme
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    volumes:
      - ./microservices/storage_service:/app
      - ./microservices/shared:/app/shared
      # Mount db_service code so memory service can import get_connection
      - ./microservices/db_service:/app/db_service

  stats_service:
    build:
      context: ./microservices/stats_service
    container_name: xavigate_stats_service
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8012"]
    ports:
      - "8012:8012"
    env_file:
      - ./microservices/stats_service/.env
    volumes:
      - ./microservices/stats_service:/app
      - ./microservices/shared:/app/shared

  db_service:
    build:
      context: ./microservices/db_service
    container_name: xavigate_db_service
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8013"]
    ports:
      - "8013:8013"
    env_file:
      - ./microservices/db_service/.env
    volumes:
      - ./microservices/db_service:/app

  auth_service:
    build:
      context: ./microservices/auth_service
    container_name: xavigate_auth_service
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8014"]
    ports:
      - "8014:8014"
    env_file:
      - ./microservices/auth_service/.env
    volumes:
      - ./microservices/auth_service:/app
  
  chat_service:
    build:
      context: ./microservices/chat_service
    container_name: xavigate_chat_service
    depends_on:
      - auth_service
      - rag_service
      - storage_service
      - stats_service
      - db_service
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8015"]
    ports:
      - "8015:8015"
    env_file:
      - ./microservices/chat_service/.env
    volumes:
      - ./microservices/chat_service:/app
      - ./microservices/shared:/app/shared
  mntest_service:
    build:
      context: ./microservices/mntest_service
    container_name: xavigate_mntest_service
    depends_on:
      - db_service
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8016"]
    ports:
      - "8016:8016"
    env_file:
      - ./microservices/mntest_service/.env
    volumes:
      - ./microservices/mntest_service:/app
      # Mount db_service code so MNTest service can import get_connection
      - ./microservices/db_service:/app/db_service
      # Mount shared code for consistency
      - ./microservices/shared:/app/shared
    environment:
      POSTGRES_DB: xavigate
      POSTGRES_USER: xavigate_user
      POSTGRES_PASSWORD: changeme
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

  nginx:
    image: nginx:stable
    container_name: xavigate_nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rag_service
      - storage_service
      - stats_service
      - db_service
      - auth_service
      - mntest_service

  postgres:
    image: ankane/pgvector
    container_name: xavigate_postgres
    restart: always
    environment:
      POSTGRES_DB: xavigate
      POSTGRES_USER: xavigate_user
      POSTGRES_PASSWORD: changeme
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  chroma:
    image: chromadb/chroma
    container_name: xavigate_chroma
    volumes:
      - chroma_data:/chroma/chroma

  jupyter:
    image: jupyter/base-notebook
    container_name: xavigate_jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''

volumes:
  pgdata:
  chroma_data:
