version: '3.8'

services:
  postgres:
    image: ankane/pgvector
    container_name: xavigate_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-xavigate}
      POSTGRES_USER: ${POSTGRES_USER:-xavigate_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - xavigate

  vector_service:
    build:
      context: ./microservices/vector_service
    container_name: xavigate_vector_service
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8017", "--root-path", "/api/vector"]
    env_file:
      - .env
    environment:
      ENV: prod
    volumes:
      - ./microservices/vector_service/maintenance:/app/maintenance
      - ./microservices/vector_service/chroma_db:/app/chroma_db
      - ./microservices/shared:/app/shared
      - ./docs:/app/docs
    networks:
      - xavigate
    restart: always

  storage_service:
    build:
      context: ./microservices/storage_service
    container_name: xavigate_storage_service
    depends_on:
      - postgres
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8011", "--root-path", "/api/storage"]
    env_file:
      - ./.env
    environment:
      ENV: prod
      POSTGRES_DB: ${POSTGRES_DB:-xavigate}
      POSTGRES_USER: ${POSTGRES_USER:-xavigate_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      DATABASE_URL: postgresql://${POSTGRES_USER:-xavigate_user}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-xavigate}
    volumes:
      - ./microservices/storage_service:/app
      - ./microservices/shared:/app/shared
    networks:
      - xavigate
    restart: always

  stats_service:
    build:
      context: ./microservices/stats_service
    container_name: xavigate_stats_service
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8012", "--root-path", "/api/stats"]
    env_file:
      - ./.env
    environment:
      ENV: prod
    volumes:
      - ./microservices/stats_service:/app
      - ./microservices/shared:/app/shared
    networks:
      - xavigate
    restart: always

  auth_service:
    build:
      context: ./microservices/auth_service
    container_name: xavigate_auth_service
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8014", "--root-path", "/api/auth"]
    env_file:
      - ./.env
    environment:
      ENV: prod
    volumes:
      - ./microservices/auth_service:/app
    networks:
      - xavigate
    restart: always
  
  chat_service:
    build:
      context: ./microservices/chat_service
    container_name: xavigate_chat_service
    depends_on:
      - auth_service
      - storage_service
      - stats_service
      - vector_service
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8015", "--root-path", "/api/chat"]
    env_file:
      - ./.env
    volumes:
      - ./microservices/chat_service:/app
      - ./microservices/shared:/app/shared
    environment:
      ENV: prod
      VECTOR_URL: http://vector_service:8017
      STORAGE_URL: http://storage_service:8011
      AUTH_SERVICE_URL: http://auth_service:8014
    networks:
      - xavigate
    restart: always

  mntest_service:
    build:
      context: ./microservices/mntest_service
    container_name: xavigate_mntest_service
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8016", "--root-path", "/api/mntest"]
    env_file:
      - ./.env
    volumes:
      - ./microservices/mntest_service:/app
      - ./microservices/shared:/app/shared
    environment:
      ENV: prod
      POSTGRES_DB: ${POSTGRES_DB:-xavigate}
      POSTGRES_USER: ${POSTGRES_USER:-xavigate_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    networks:
      - xavigate
    restart: always

volumes:
  pgdata:

networks:
  xavigate:
    driver: bridge