
services:
  postgres:
    image: ankane/pgvector
    container_name: xavigate_postgres
    restart: always
    environment:
      POSTGRES_DB: xavigate
      POSTGRES_USER: xavigate_user
      POSTGRES_PASSWORD: changeme
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - xavigate

  vector_service:
    build:
      context: ./microservices/vector_service
    container_name: xavigate_vector_service
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8017"]
    ports:
      - "8017:8017"
    env_file:
      - .env
      - ./microservices/vector_service/.env
    volumes:
      - ./microservices/vector_service/maintenance:/app/maintenance
      - ./microservices/vector_service/chroma_db:/app/chroma_db
      - ./microservices/shared:/app/shared
      - ./docs:/app/docs
    networks:
      - xavigate

  storage_service:
    build:
      context: ./microservices/storage_service
    container_name: xavigate_storage_service
    depends_on:
      - postgres
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8011"]
    ports:
      - "8011:8011"
    env_file:
      - ./.env
      - ./microservices/storage_service/.env
    environment:
      POSTGRES_DB: xavigate
      POSTGRES_USER: xavigate_user
      POSTGRES_PASSWORD: changeme
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    volumes:
      - ./microservices/storage_service:/app
      - ./microservices/shared:/app/shared
    networks:
      - xavigate

  stats_service:
    build:
      context: ./microservices/stats_service
    container_name: xavigate_stats_service
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8012"]
    ports:
      - "8012:8012"
    env_file:
      - ./microservices/stats_service/.env
    volumes:
      - ./microservices/stats_service:/app
      - ./microservices/shared:/app/shared
    networks:
      - xavigate

  auth_service:
    build:
      context: ./microservices/auth_service
    container_name: xavigate_auth_service
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8014"]
    ports:
      - "8014:8014"
    env_file:
      - ./microservices/auth_service/.env
    volumes:
      - ./microservices/auth_service:/app
    networks:
      - xavigate
  
  chat_service:
    build:
      context: ./microservices/chat_service
    container_name: xavigate_chat_service
    depends_on:
      - auth_service
      - storage_service
      - stats_service
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8015"]
    ports:
      - "8015:8015"
    env_file:
      - ./microservices/chat_service/.env
    volumes:
      - ./microservices/chat_service:/app
      - ./microservices/shared:/app/shared
    environment:
      RAG_URL: http://vector_service:8017
      STORAGE_URL: http://storage_service:8011
    networks:
      - xavigate
  mntest_service:
    build:
      context: ./microservices/mntest_service
    container_name: xavigate_mntest_service
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8016"]
    ports:
      - "8016:8016"
    env_file:
      - ./microservices/mntest_service/.env
    volumes:
      - ./microservices/mntest_service:/app
      - ./microservices/shared:/app/shared
    environment:
      POSTGRES_DB: xavigate
      POSTGRES_USER: xavigate_user
      POSTGRES_PASSWORD: changeme
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    networks:
      - xavigate

volumes:
  pgdata:

networks:
  xavigate:
    driver: bridge
